name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours (optional)
  workflow_dispatch:        # allow manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake (light + dark)
        # <-- full action (not svg-only)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
