name: Update Visitor Badge

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 min
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update timestamp in README
        run: |
          TS=$(date +%s)
          sed -i "s|\(api/badges/mybadge/svg?ts=\)[0-9]*|\1$TS|" README.md
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update visitor badge timestamp [skip ci]" || echo "No changes"
          git push
